# exception handling in python


print('exceptin handling in python')